; ============================================================
;  EPOS CubeSat — ADCS + TT&C
;  Dois ambientes: 'satelite' e 'estacao', cada um compila
;  apenas o main.cpp correspondente, compartilhando lib/ e include/.
; ============================================================

[platformio]
default_envs = satelite

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    hideakitai/MPU9250 @ ^0.4.8
    https://github.com/xreef/LoRa_E32_Series_Library.git

[env:satelite]
build_src_filter = +<main_satelite.cpp> -<main_estacao.cpp>

[env:estacao]
build_src_filter = +<main_estacao.cpp> -<main_satelite.cpp>
